### ISSUE TITLE
Design Paper Revisions

### ISSUE THREAD

**Issue by LouisNajdek** [Awesomehood/RansomwareDefenseSmallOrg#15]

**Comment by JoFiiiN** [comment]
Re-submitted for assessment. Will re-open if there are additional revisions.

**Comment by JoFiiiN** [comment]
https://docs.google.com/document/d/1wE0iDHu9hvqjIOdrRKGdg_zEDXb8z8XgHmHLyr8U8eE/edit - Link to paper to follow as it is updated
