### ISSUE TITLE
Sprint 2: First Draft for Guide

### ISSUE THREAD

**Issue by BitterCandies** [Awesomehood/RansomwareDefenseSmallOrg#32]
For this task, we want to try to have as much of the guide written as possible in a first draft. Absolutely does not need to be perfect or formatted even, but there should be something in there to reflect on.

**Comment by LouisNajdek** [comment]
Here is a link to a draft for the end user guide.

https://docs.google.com/document/d/19u9_FfKVdTfL2wUjxNNYwQwHewUGUPQ5kHEI4XT0hJw/edit?usp=sharing

**Comment by LouisNajdek** [comment]
Here is a link to a draft for the System Administrator guide: https://docs.google.com/document/d/14O_b6WyPPC-tWOczQWiziIl9KSkqiDxiiixiVIwiQd0/edit?usp=sharing
