### ISSUE TITLE
Sprint 2: Final Drafts for Guide

### ISSUE THREAD

**Issue by BitterCandies** [Awesomehood/RansomwareDefenseSmallOrg#36]

**Comment by LouisNajdek** [comment]
The draft's will be contained in these two documents:

System-Administrator Draft: https://docs.google.com/document/d/14O_b6WyPPC-tWOczQWiziIl9KSkqiDxiiixiVIwiQd0/edit

End-User Draft: https://docs.google.com/document/d/19u9_FfKVdTfL2wUjxNNYwQwHewUGUPQ5kHEI4XT0hJw/edit

**Comment by LouisNajdek** [comment]
Updated the End-User draft

**Comment by Awesomehood** [comment]
Closing because the spirit 4 task covers this one, so this does not need to be here. Closed for organizational cleanness.
