### ISSUE TITLE
Sprint 2: Getting our VMs ready for testing 

### ISSUE THREAD

**Issue by Awesomehood** [Awesomehood/RansomwareDefenseSmallOrg#46]
Setting up the VMs that we will be using for testing

**Comment by LouisNajdek** [comment]
I believe the VMs we should use are a Centos 7 attacker machine and a Windows 10 victim machine to demonstrate a ransomware attack, with the executable being downloaded from a phishing email sent to the victim during the demonstration.

**Comment by JoFiiiN** [comment]
Met with Joe Williams and he told us that we are all set to test on the Leahy Center's testing network. We have sent our list of VM requests over and will begin setup/testing once they are ready to go.

**Comment by JoFiiiN** [comment]
Louis and I will create the VMs at the Leahy Center on Monday, 3/7. From here we will make sure that everyone is able to connect to them remotely so that we are able to work virtually and not have to be on-site at the Leahy Center to get our testing done.

**Comment by Awesomehood** [comment]
Ransomware demo'd using VM's I would say this is accomplished.
