### ISSUE TITLE
Meet with Joe - 1.2 Update Meeting

### ISSUE THREAD

**Issue by JoFiiiN** [Awesomehood/RansomwareDefenseSmallOrg#48]
The meeting is scheduled for 2/10 @ 2:30 pm in Joe's Office. The meeting is to discuss updates on the Kanban board, and what has been accomplished since the last meeting.

**Comment by LouisNajdek** [comment]
On 2/11/2022, we had a 9:00am meeting with Joe Williams of the Leahy Center.

Joe's goal for the project is internal use and client training for the Leahy Center, and approved of there being two videos. He additionally requested there be a powerpoint or word document that can be referred to by the trainees. 

Our testing environment will be able to be setup by emailing the Leahy Center support email with our specifications, which will Joe will make sure goes directly to the IT team for creation.

Going forward, email is Joe's preferred method of update.
