### ISSUE TITLE
Connect with Client - Adam

### ISSUE THREAD

**Issue by Awesomehood** [Awesomehood/RansomwareDefenseSmallOrg#5]

**Comment by LouisNajdek** [comment]
Results of Meeting #1 with Adam:
We all are going to figure out what specifically as it relates to mitigation/recovery/technical analysis  we want to research individually and how to make that information useful for a small-medium sized business. That information will then be put together as a group. 
We will be having another meeting with Adam next week to discuss our findings and plan our trajectory from there.
