### ISSUE TITLE
Sprint 2.2 Update Meeting

### ISSUE THREAD

**Issue by JoFiiiN** [Awesomehood/RansomwareDefenseSmallOrg#50]
Meeting on 3/3 at 2:15 for Sprint 2 update meeting

**Comment by JoFiiiN** [comment]
![image](https://user-images.githubusercontent.com/54647546/155595197-7567dca4-c55a-49d4-8ccb-a292044b864b.png)

**Comment by BitterCandies** [comment]
Met with Joe to discuss our current status and our future plans. We are currently focused very heavily on getting our video script drafts ready, and creating our VMs this upcoming Monday (3/7). Once these are done we will perform practice tests on our VMs to ensure we have everything working properly, and then record our demo. Our script drafts should be done by the top of Spring break (3/14), which will give us a good amount of time to then revise, and record when we return from break.
