### ISSUE TITLE
Connect with Client - Joe W.

### ISSUE THREAD

**Issue by Awesomehood** [Awesomehood/RansomwareDefenseSmallOrg#6]

**Comment by JoFiiiN** [comment]
![Meeting Info - Joe Williams](https://user-images.githubusercontent.com/54647546/138206133-cfe4c67f-e962-4037-9df5-a83000fe58ae.PNG)

**Comment by BitterCandies** [comment]
Colton and I were able to make it and we talked with  Joe about what he would be expecting from us in terms of getting the ransomware defense guides/reports/demos out to the clients. He said it would be good if we could focus on the aspects of ransomware that would be more client-side like what forms it comes in most often, what it would look like to click on a ransomware link, and what kind of training might clients be able to do to avoid it. That could likely be the main focus of our RanDef guide and then we would add other things as we see fit/if we have the time. Written reports would suffice but a video presentation/demonstration would be much more preferable (in addition to a written/screenshot type of report).
